from enum import Enum, auto


PICKLE_FILE = ".pickle.positions"


class NGUButtons(Enum):
    EMPTY_AREA = auto()
    MENU_BASICTRAINING = auto()
    MENU_FIGHTBOSS = auto()
    MENU_MONEYPIT = auto()
    MENU_ADVENTURE = auto()
    MENU_INVENTORY = auto()
    MENU_AUGMENTATION = auto()
    MENU_ADVTRAINING = auto()
    MENU_TIMEMACHINE = auto()
    MENU_BLOODMAGIC = auto()
    ATTACK1_PLUS = auto()
    ATTACK1_MINUS = auto()
    ATTACK1_CAP = auto()
    ATTACK2_PLUS = auto()
    ATTACK2_MINUS = auto()
    ATTACK2_CAP = auto()
    ATTACK3_PLUS = auto()
    ATTACK3_MINUS = auto()
    ATTACK3_CAP = auto()
    ATTACK4_PLUS = auto()
    ATTACK4_MINUS = auto()
    ATTACK4_CAP = auto()
    ATTACK5_PLUS = auto()
    ATTACK5_MINUS = auto()
    ATTACK5_CAP = auto()
    ATTACK6_PLUS = auto()
    ATTACK6_MINUS = auto()
    ATTACK6_CAP = auto()
    DEFENSE1_PLUS = auto()
    DEFENSE1_MINUS = auto()
    DEFENSE1_CAP = auto()
    DEFENSE2_PLUS = auto()
    DEFENSE2_MINUS = auto()
    DEFENSE2_CAP = auto()
    DEFENSE3_PLUS = auto()
    DEFENSE3_MINUS = auto()
    DEFENSE3_CAP = auto()
    DEFENSE4_PLUS = auto()
    DEFENSE4_MINUS = auto()
    DEFENSE4_CAP = auto()
    DEFENSE5_PLUS = auto()
    DEFENSE5_MINUS = auto()
    DEFENSE5_CAP = auto()
    DEFENSE6_PLUS = auto()
    DEFENSE6_MINUS = auto()
    DEFENSE6_CAP = auto()
    ENERGY_INFINITE = auto()
    MENU_REBIRTH = auto()
    MENU_REBIRTH_REBIRTH = auto()
    MENU_REBIRTH_CONFIRM = auto()
    MENU_SPENDEXP = auto()
    MENU_FIGHTBOSS_NUKE = auto()
    MENU_FIGHTBOSS_STOP = auto()
    MENU_FIGHTBOSS_FIGHT = auto()
    MENU_MONEYPIT_FEED = auto()
    MENU_MONEYPIT_FEEDCONFIRM = auto()
    MENU_ADVENTURE_IDLEMODE = auto()
    MENU_ADVENTURE_NEXT = auto()
    MENU_ADVENTURE_SCROLLBAR = auto()
    MENU_ADVENTURE_SCROLLFOREST = auto()
    MENU_ADVENTURE_SCROLLCAVE = auto()
